// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuE-g1AtMOQlamusI9QKwfGF0fQaj7030',
    appId: '1:103783745615:web:829234fbe0bc736984823a',
    messagingSenderId: '103783745615',
    projectId: 'zt-authcrud',
    authDomain: 'zt-authcrud.firebaseapp.com',
    storageBucket: 'zt-authcrud.appspot.com',
    measurementId: 'G-P69RKSGXSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6v0YrhwW63U4kd_DNATOx20z-mNslzY',
    appId: '1:103783745615:android:cbdfdfaa3db0d69384823a',
    messagingSenderId: '103783745615',
    projectId: 'zt-authcrud',
    storageBucket: 'zt-authcrud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFOXVMXCU7AiJMuYHVPsxQv9Y53sU3Ezs',
    appId: '1:103783745615:ios:79980e05e6c3ca3484823a',
    messagingSenderId: '103783745615',
    projectId: 'zt-authcrud',
    storageBucket: 'zt-authcrud.appspot.com',
    iosBundleId: 'com.example.zoogFlutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFOXVMXCU7AiJMuYHVPsxQv9Y53sU3Ezs',
    appId: '1:103783745615:ios:8fe01af61cf74e4184823a',
    messagingSenderId: '103783745615',
    projectId: 'zt-authcrud',
    storageBucket: 'zt-authcrud.appspot.com',
    iosBundleId: 'com.example.zoogFlutterCrud.RunnerTests',
  );
}
